version: "3.8"
services:
  gateway:
    image: jyguru/biked-integration-gateway:${RELEASE_TAG}
    build:
      context: ./
      dockerfile: gateway.dockerfile
  service:
    image: jyguru/biked-integration-beta:${RELEASE_TAG}
    build:
      context: ./
      dockerfile: service.dockerfile
