# syntax=docker/dockerfile:1
FROM python:3.9-slim-buster
WORKDIR /app
COPY service_resources/ service_resources/
COPY requirements.txt requirements.txt
RUN apt-get update -y && apt-get upgrade -y && apt-get install libgomp1 -y
RUN pip3 install -r requirements.txt