version: "3.8"
services:
  gateway:
    image: jyguru/biked-integration-gateway:03jan2024
    ports:
      - "8080:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
  integration-service:
    image: jyguru/biked-integration-beta:17nov2023
    hostname: integration-service
    entrypoint: sh ./run.sh
    healthcheck:
      test: curl --fail integration-service:80/health || exit 1
      interval: 10s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
