name: Push docker image
on:
  workflow_dispatch:
    inputs:
      RELEASE_TAG:
        description: "Enter desired release tag"
        required: true
jobs:
  push_docker_image:
    name: Push Docker image
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${ { github.event.inputs.RELEASE_TAG } }
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Compose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: KengoTODA/actions-setup-docker-compose@v1
      - name: build image
        run: docker-compose build service
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push image
        run: docker push jyguru/biked-integration-beta:$RELEASE_TAG
