name: Verify Code
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
jobs:
  verify_code:
    name: Verify
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: SNAPSHOT

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Compose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: KengoTODA/actions-setup-docker-compose@v1
      - name: build image
        run: docker-compose build service
      - name: run tests
        run: docker run --entrypoint './test.sh' jyguru/biked-integration-beta:$RELEASE_TAG -itd
